### ISSUE TITLE
Amazon Public SNS subscribe issue

### ISSUE THREAD

**Issue by heathhenley** [CI-CMG/pointstore-api-docs#2]
First, thanks for all the public csb data efforts! 

I was trying to subscribe to the public notification here: https://noaa-dcdb-bathymetry-pds.s3.amazonaws.com/docs/readme.html (arn:aws:sns:us-east-1:709902155096:NewDCDBBathymetryObject) - but I'm getting a permission error: 

![image](https://github.com/user-attachments/assets/1369aa4f-4020-40f5-a8c6-263cfde8699d)

I'm a noob with AWS so this might be my issue, though I successfully subscribed to another public sns topic as a test. When I was googling around it seemed like this is related to resource based policy settings on the actual topic. If this is just skill issue sorry to waste your time.

**Comment by jccartwright** [comment]
Hi Heath, I just tested this again using a new Lambda in an account w/o any association to the NODD or CSB and it seems to work fine. I'm guessing that it's an issue w/ the permissions of the role used to execute your Lambda. I can't explain why it worked w/ another SNS topic.

Here's the ARN I used: 
arn:aws:sns:us-east-1:709902155096:NewDCDBBathymetryObject

Without being able to reproduce the problem, I don't know there's a lot I can do to help but if you can share the IAM policies/trust relationships on the role creating the subscription, I'll take a quick look

**Comment by heathhenley** [comment]
Thanks for the help and for confirming, I'll give it another go it later tonight / try a new iam account etc, good that it seems like it must be on my end. 

One maybe difference (?) is I'm trying to have it hit an external https endpoint (I'm picking 'https' under protocol), not sure if that makes a difference versus pointing it at an internal lambda.

**Comment by heathhenley** [comment]
Ok so oddly, I can also use the "Lambda" policy to subscribe to the topic, so worst case this is non-issue, I'll just trigger my apps using the lambda as an adapter. Though I haven't actually seen it get triggered yet, which is a little suspicious but it appears to be subscribed...
For example: 
![image](https://github.com/user-attachments/assets/9c8484e5-23f3-4472-8218-de3a7ac2ade5)

I did try the following though: 
Made a new IAM user ("sns_test") with the following permissions
``` json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "sns:*",
            "Resource": "*"
        }
    ]
}
```
and then logged in as that user and try to subscribe to the topic using "https" protocol instead of lambda: 

![image](https://github.com/user-attachments/assets/6e35920e-45f3-4948-a0d6-8180b0934a94)

Another weird thing is that when using https as the protocol, I can't find the topic arn unless I'm set to the same region. This didn't matter for the Lambda.

**Comment by jccartwright** [comment]
The data are uploaded to the [S3 bucket](https://noaa-dcdb-bathymetry-pds.s3.amazonaws.com/index.html#csb/csv) every 6 hours (assuming data have arrived at the DCDB during that time window)

I'm going to close this issue as I don't see anything wrong w/ the S3 event topic. I've used SNS messages to trigger Lambdas, connect to SQS queues, send email, and initiate step functions but don't have any experience using SNS messages over the HTTPS protocol. Sorry I couldn't be of more help

**Comment by heathhenley** [comment]
Thanks for taking a look, I'll just use the lambda.
